"use server";
import { revalidatePath } from "next/cache";
import { prisma, TaskStatus } from "@marketplace-engine/database";
import { crmLeadIdempotencyKey } from "@marketplace-engine/crm-client";
import { z } from "zod";

const taskActionSchema=z.object({taskId:z.string().min(1),action:z.enum(["sent","skip","snooze"]),finalMessage:z.string().max(400).optional(),notes:z.string().max(2000).optional()});
export async function updateTask(formData:FormData){const input=taskActionSchema.parse(Object.fromEntries(formData));const task=await prisma.outreachTask.findUniqueOrThrow({where:{id:input.taskId},include:{opportunity:{include:{listing:true}}}});const now=new Date();if(input.action==="sent"){const actualMessage=(input.finalMessage||task.suggestedMessage).trim();await prisma.$transaction([prisma.outreachTask.update({where:{id:task.id},data:{status:TaskStatus.SENT,finalMessage:actualMessage,completedAt:now,notes:input.notes??null}}),prisma.contactAttempt.create({data:{opportunityId:task.opportunityId,sellerId:task.opportunity.listing.sellerId,repId:task.assignedRepId,channel:"facebook_marketplace",templateVersion:"v1",actualMessage,sentManually:true,sentAt:now,notes:input.notes??null}}),...(task.opportunity.listing.sellerId?[prisma.sellerProfile.update({where:{id:task.opportunity.listing.sellerId},data:{previousOutreachCount:{increment:1},lastOutreachAt:now}})]:[]),prisma.auditEvent.create({data:{actorId:task.assignedRepId,eventType:"outreach_marked_sent",entityType:"OutreachTask",entityId:task.id,payload:{manual:true}}})]);}else if(input.action==="skip"){await prisma.outreachTask.update({where:{id:task.id},data:{status:TaskStatus.SKIPPED,completedAt:now,skipReason:input.notes??"rep_skipped",followUpEligibility:false}});}else{await prisma.outreachTask.update({where:{id:task.id},data:{status:TaskStatus.SNOOZED,snoozedUntil:new Date(now.getTime()+86400000),notes:input.notes??null}});}revalidatePath("/outreach");revalidatePath("/");}

const conversationSchema=z.object({taskId:z.string().min(1),conversationUrl:z.string().url().refine(value=>{try{return new URL(value).hostname.endsWith("facebook.com")}catch{return false}},{message:"Use a facebook.com conversation URL"})});
export async function saveConversationUrl(formData:FormData){const input=conversationSchema.parse(Object.fromEntries(formData));await prisma.outreachTask.update({where:{id:input.taskId},data:{conversationUrl:input.conversationUrl}});await prisma.auditEvent.create({data:{eventType:"conversation_url_saved",entityType:"OutreachTask",entityId:input.taskId,payload:{manual:true}}});revalidatePath("/outreach");}

const replySchema=z.object({taskId:z.string(),responseStatus:z.enum(["no_response","positive_response","maybe_later","asked_for_price","asked_for_phone_call","provided_phone","provided_email","requested_estimate","booked","not_interested","wrong_person","spam_complaint","seller_blocked_us","listing_removed"]),notes:z.string().max(2000).optional()});
export async function recordReply(formData:FormData){const input=replySchema.parse(Object.fromEntries(formData));const task=await prisma.outreachTask.findUniqueOrThrow({where:{id:input.taskId},include:{opportunity:{include:{listing:true}}}});const negative=["not_interested","wrong_person","spam_complaint","seller_blocked_us"].includes(input.responseStatus);await prisma.$transaction(async(tx)=>{const contact=await tx.contactAttempt.findFirst({where:{opportunityId:task.opportunityId},orderBy:{sentAt:"desc"}});if(contact)await tx.contactAttempt.update({where:{id:contact.id},data:{responseStatus:input.responseStatus,responseAt:new Date(),notes:input.notes??null}});await tx.outreachTask.update({where:{id:task.id},data:{result:input.responseStatus,followUpEligibility:input.responseStatus==="maybe_later"}});if(input.responseStatus==="listing_removed")await tx.listing.update({where:{id:task.opportunity.listing.id},data:{status:"REMOVED"}});if(negative&&task.opportunity.listing.sellerId){await tx.sellerProfile.update({where:{id:task.opportunity.listing.sellerId},data:{suppressionStatus:true,suppressionReason:input.responseStatus}});await tx.suppressionRecord.create({data:{sellerId:task.opportunity.listing.sellerId,listingId:task.opportunity.listing.id,sourceId:task.opportunity.listing.sourceId,suppressionType:"negative_response",reason:input.responseStatus,permanent:true}});}await tx.auditEvent.create({data:{actorId:task.assignedRepId,eventType:"reply_recorded",entityType:"Opportunity",entityId:task.opportunityId,payload:{responseStatus:input.responseStatus}}});});revalidatePath("/outreach");}

const leadSchema=z.object({taskId:z.string(),name:z.string().max(200).optional(),phone:z.string().max(40).optional(),email:z.string().email().optional().or(z.literal("")),originCity:z.string().max(200).optional(),destinationCity:z.string().max(200).optional()});
export async function createLead(formData:FormData){const input=leadSchema.parse(Object.fromEntries(formData));const task=await prisma.outreachTask.findUniqueOrThrow({where:{id:input.taskId},include:{opportunity:{include:{listing:true}}}});const key=crmLeadIdempotencyKey({source:"facebook_marketplace",sourceListingId:task.opportunity.listing.externalListingId,territoryId:task.opportunity.territoryId});const values={name:input.name??null,phone:input.phone??null,email:input.email||null,originCity:input.originCity??null,destinationCity:input.destinationCity??null};await prisma.lead.upsert({where:{opportunityId:task.opportunityId},update:values,create:{opportunityId:task.opportunityId,sourceId:task.opportunity.listing.sourceId,idempotencyKey:key,...values,serviceType:task.opportunity.estimatedServiceType,qualificationStatus:"qualified",leadStatus:"new"}});await prisma.opportunity.update({where:{id:task.opportunityId},data:{qualificationStatus:"CONVERTED"}});revalidatePath("/");revalidatePath("/outreach");}

export async function suppressSeller(formData:FormData){const taskId=z.string().parse(formData.get("taskId"));const task=await prisma.outreachTask.findUniqueOrThrow({where:{id:taskId},include:{opportunity:{include:{listing:true}}}});if(!task.opportunity.listing.sellerId)throw new Error("This listing has no stable seller ID; suppress the listing instead.");await prisma.$transaction([prisma.sellerProfile.update({where:{id:task.opportunity.listing.sellerId},data:{suppressionStatus:true,suppressionReason:"manual_do_not_contact"}}),prisma.suppressionRecord.create({data:{sellerId:task.opportunity.listing.sellerId,listingId:task.opportunity.listing.id,sourceId:task.opportunity.listing.sourceId,suppressionType:"do_not_contact",reason:"Manual rep suppression",permanent:true}}),prisma.outreachTask.updateMany({where:{opportunity:{listing:{sellerId:task.opportunity.listing.sellerId}},status:{in:[TaskStatus.READY,TaskStatus.SNOOZED]}},data:{status:TaskStatus.CANCELLED,followUpEligibility:false,completedAt:new Date()}})]);revalidatePath("/outreach");}
