"use server";
import { revalidatePath } from "next/cache";
import { prisma, TaskStatus } from "@marketplace-engine/database";
import { crmLeadIdempotencyKey } from "@marketplace-engine/crm-client";
import { z } from "zod";
import {headers} from "next/headers";
import {proofBucket} from "../lib/proof-storage";

async function currentIdentity(){const values=await headers();return {role:values.get("x-marketplace-role"),email:values.get("x-marketplace-user-email")}}

const skipReasons=["listing_removed","not_a_fit","competitor","duplicate","already_contacted","outside_service_area","other"] as const;
const taskActionSchema=z.object({taskId:z.string().min(1),action:z.enum(["sent","skip","snooze"]),finalMessage:z.string().max(400).optional(),notes:z.string().max(2000).optional(),skipReason:z.enum(skipReasons).optional()}).superRefine((value,context)=>{if(value.action==="skip"&&!value.skipReason)context.addIssue({code:"custom",path:["skipReason"],message:"Select a skip reason"})});
export async function claimTask(formData:FormData){const taskId=z.string().parse(formData.get("taskId")),identity=await currentIdentity();if(identity.role!=="MARKETPLACE_REP"||!identity.email)throw new Error("Rep identity required");const actor=await prisma.user.findUniqueOrThrow({where:{email:identity.email}}),now=new Date(),result=await prisma.outreachTask.updateMany({where:{id:taskId,status:{in:[TaskStatus.READY,TaskStatus.SNOOZED]},OR:[{claimedById:null},{claimExpiresAt:{lt:now}},{claimedById:actor.id}]},data:{claimedById:actor.id,claimedAt:now,claimExpiresAt:new Date(now.getTime()+30*60_000)}});if(result.count!==1)throw new Error("Another rep has already claimed this opportunity");await prisma.auditEvent.create({data:{actorId:actor.id,eventType:"outreach_claimed",entityType:"OutreachTask",entityId:taskId,payload:{expiresInMinutes:30}}});revalidatePath("/outreach")}
export async function updateTask(formData:FormData){
  const input=taskActionSchema.parse(Object.fromEntries(formData)),identity=await currentIdentity();
  if(identity.role==="MARKETPLACE_REP"&&!(["sent","skip"] as string[]).includes(input.action))throw new Error("This account only has send and skip access");
  const task=await prisma.outreachTask.findUniqueOrThrow({where:{id:input.taskId},include:{opportunity:{include:{listing:{include:{source:true}}}}}}),actor=identity.email?await prisma.user.findUnique({where:{email:identity.email}}):null,now=new Date();
  if(identity.role==="MARKETPLACE_REP"&&(task.claimedById!==actor?.id||!task.claimExpiresAt||task.claimExpiresAt<now))throw new Error("Claim this opportunity before completing it");
  if(input.action==="sent"){
    const actualMessage=(input.finalMessage||task.suggestedMessage).trim(),actorId=actor?.id??task.assignedRepId,proofValue=formData.get("proof"),proof=proofValue instanceof File&&proofValue.size>0?proofValue:null;
    if(identity.role==="MARKETPLACE_REP"&&!proof)throw new Error("Upload a screenshot proving the message was sent");
    if(proof&&(!["image/png","image/jpeg","image/webp"].includes(proof.type)||proof.size>5_000_000))throw new Error("Proof must be a PNG, JPEG, or WebP image under 5 MB");
    let proofData:{storageKey:string;mimeType:string;sizeBytes:number}|null=null;if(proof){if(!actorId)throw new Error("An identified rep is required for proof upload");const storageKey=`outreach/${task.id}/${crypto.randomUUID()}`;await proofBucket().put(storageKey,await proof.arrayBuffer(),{httpMetadata:{contentType:proof.type}});proofData={storageKey,mimeType:proof.type,sizeBytes:proof.size}}
    await prisma.$transaction([prisma.outreachTask.update({where:{id:task.id},data:{status:TaskStatus.SENT,finalMessage:actualMessage,completedAt:now,notes:input.notes??null}}),prisma.contactAttempt.create({data:{opportunityId:task.opportunityId,sellerId:task.opportunity.listing.sellerId,repId:actorId,channel:task.opportunity.listing.source.type,templateVersion:"v1",actualMessage,sentManually:true,sentAt:now,notes:input.notes??null}}),...(task.opportunity.listing.sellerId?[prisma.sellerProfile.update({where:{id:task.opportunity.listing.sellerId},data:{previousOutreachCount:{increment:1},lastOutreachAt:now}})]:[]),...(proofData&&actorId?[prisma.outreachProof.create({data:{taskId:task.id,uploadedById:actorId,...proofData}})]:[]),prisma.auditEvent.create({data:{actorId,eventType:"outreach_marked_sent",entityType:"OutreachTask",entityId:task.id,payload:{manual:true,source:task.opportunity.listing.source.type,repEmail:identity.email,proofAttached:Boolean(proofData)}}})]);
  }else if(input.action==="skip")await prisma.outreachTask.update({where:{id:task.id},data:{status:TaskStatus.SKIPPED,completedAt:now,skipReason:input.skipReason!,notes:input.notes??null,followUpEligibility:false}});
  else await prisma.outreachTask.update({where:{id:task.id},data:{status:TaskStatus.SNOOZED,snoozedUntil:new Date(now.getTime()+86400000),notes:input.notes??null}});
  revalidatePath("/outreach");revalidatePath("/");
}

const conversationSchema=z.object({taskId:z.string().min(1),conversationUrl:z.string().url().refine(value=>{try{const host=new URL(value).hostname;return host.endsWith("facebook.com")||host.endsWith("kijiji.ca")}catch{return false}},{message:"Use a facebook.com or kijiji.ca URL"})});
export async function saveConversationUrl(formData:FormData){const input=conversationSchema.parse(Object.fromEntries(formData));await prisma.outreachTask.update({where:{id:input.taskId},data:{conversationUrl:input.conversationUrl}});await prisma.auditEvent.create({data:{eventType:"conversation_url_saved",entityType:"OutreachTask",entityId:input.taskId,payload:{manual:true}}});revalidatePath("/outreach");}

const replySchema=z.object({taskId:z.string(),responseStatus:z.enum(["no_response","positive_response","maybe_later","asked_for_price","asked_for_phone_call","provided_phone","provided_email","requested_estimate","booked","not_interested","wrong_person","spam_complaint","seller_blocked_us","listing_removed"]),notes:z.string().max(2000).optional()});
export async function recordReply(formData:FormData){const input=replySchema.parse(Object.fromEntries(formData));const task=await prisma.outreachTask.findUniqueOrThrow({where:{id:input.taskId},include:{opportunity:{include:{listing:true}}}});const negative=["not_interested","wrong_person","spam_complaint","seller_blocked_us"].includes(input.responseStatus);await prisma.$transaction(async(tx)=>{const contact=await tx.contactAttempt.findFirst({where:{opportunityId:task.opportunityId},orderBy:{sentAt:"desc"}});if(contact)await tx.contactAttempt.update({where:{id:contact.id},data:{responseStatus:input.responseStatus,responseAt:new Date(),notes:input.notes??null}});await tx.outreachTask.update({where:{id:task.id},data:{result:input.responseStatus,followUpEligibility:["no_response","maybe_later"].includes(input.responseStatus)}});if(input.responseStatus==="listing_removed")await tx.listing.update({where:{id:task.opportunity.listing.id},data:{status:"REMOVED"}});if(negative&&task.opportunity.listing.sellerId){await tx.sellerProfile.update({where:{id:task.opportunity.listing.sellerId},data:{suppressionStatus:true,suppressionReason:input.responseStatus}});await tx.suppressionRecord.create({data:{sellerId:task.opportunity.listing.sellerId,listingId:task.opportunity.listing.id,sourceId:task.opportunity.listing.sourceId,suppressionType:"negative_response",reason:input.responseStatus,permanent:true}});}await tx.auditEvent.create({data:{actorId:task.assignedRepId,eventType:"reply_recorded",entityType:"Opportunity",entityId:task.opportunityId,payload:{responseStatus:input.responseStatus}}});});revalidatePath("/outreach");}

const leadSchema=z.object({taskId:z.string(),name:z.string().max(200).optional(),phone:z.string().max(40).optional(),email:z.string().email().optional().or(z.literal("")),originCity:z.string().max(200).optional(),destinationCity:z.string().max(200).optional(),contactSource:z.string().max(100).optional(),contactPermissionStatus:z.enum(["UNVERIFIED_PUBLIC_LISTING","EXPRESS_CONSENT","EXISTING_BUSINESS_RELATIONSHIP","BUSINESS_NUMBER"]).default("UNVERIFIED_PUBLIC_LISTING")});
export async function createLead(formData:FormData){const input=leadSchema.parse(Object.fromEntries(formData));const task=await prisma.outreachTask.findUniqueOrThrow({where:{id:input.taskId},include:{opportunity:{include:{listing:{include:{source:true}}}}}});const key=crmLeadIdempotencyKey({source:task.opportunity.listing.source.type,sourceListingId:task.opportunity.listing.externalListingId,territoryId:task.opportunity.territoryId});const values={name:input.name??null,phone:input.phone??null,email:input.email||null,originCity:input.originCity??null,destinationCity:input.destinationCity??null,contactSource:input.contactSource??null,contactPermissionStatus:input.contactPermissionStatus};await prisma.lead.upsert({where:{opportunityId:task.opportunityId},update:values,create:{opportunityId:task.opportunityId,sourceId:task.opportunity.listing.sourceId,idempotencyKey:key,...values,serviceType:task.opportunity.estimatedServiceType,qualificationStatus:"qualified",leadStatus:"new"}});await prisma.opportunity.update({where:{id:task.opportunityId},data:{qualificationStatus:"CONVERTED"}});revalidatePath("/");revalidatePath("/outreach");}

export async function suppressSeller(formData:FormData){const taskId=z.string().parse(formData.get("taskId"));const task=await prisma.outreachTask.findUniqueOrThrow({where:{id:taskId},include:{opportunity:{include:{listing:true}}}});if(!task.opportunity.listing.sellerId)throw new Error("This listing has no stable seller ID; suppress the listing instead.");await prisma.$transaction([prisma.sellerProfile.update({where:{id:task.opportunity.listing.sellerId},data:{suppressionStatus:true,suppressionReason:"manual_do_not_contact"}}),prisma.suppressionRecord.create({data:{sellerId:task.opportunity.listing.sellerId,listingId:task.opportunity.listing.id,sourceId:task.opportunity.listing.sourceId,suppressionType:"do_not_contact",reason:"Manual rep suppression",permanent:true}}),prisma.outreachTask.updateMany({where:{opportunity:{listing:{sellerId:task.opportunity.listing.sellerId}},status:{in:[TaskStatus.READY,TaskStatus.SNOOZED]}},data:{status:TaskStatus.CANCELLED,followUpEligibility:false,completedAt:new Date()}})]);revalidatePath("/outreach");}
