import "dotenv/config";
import { PgBoss, type Job } from "pg-boss";
import pino from "pino";
import { prisma, ingestSearchResults, createManualSourceTask, TaskStatus, TaskType } from "@marketplace-engine/database/node";
import { StdioMcpTransport, FacebookMarketplaceAdapter, ApifyKijijiAdapter, type MarketplaceSource } from "@marketplace-engine/marketplace-source";
import { haversineKm, toFacebookSearchPoints, validateGeographySeeds, type RegionKey } from "@marketplace-engine/geography";
import { evaluateFollowUp } from "@marketplace-engine/operations";
import { crmLeadIdempotencyKey, StubCrmClient, WebhookCrmClient } from "@marketplace-engine/crm-client";
import {createListingClassifier} from "@marketplace-engine/intelligence";
import {sendDailySummary,sendOpportunityDigest,sendSourceHealthAlert} from "./email-alerts.js";

const log=pino({level:process.env.LOG_LEVEL??"info",redact:{paths:["*.password","*.token","*.cookies","DATABASE_URL","FACEBOOK_MCP_ARGS","CRM_WEBHOOK_SECRET"],censor:"[REDACTED]"}});
function requiredEnv(name:string){const value=process.env[name];if(!value)throw new Error(`${name} is required`);return value}
const databaseUrl=process.env.DIRECT_URL||requiredEnv("DATABASE_URL");
const queueDatabaseUrl=databaseUrl.replace(/([?&])sslmode=require(&|$)/,(_match,prefix:string,suffix:string)=>suffix?prefix:"");
const phone=requiredEnv("SATURN_STAR_PHONE");
const command=process.env.FACEBOOK_MCP_COMMAND??"node";const args=(process.env.FACEBOOK_MCP_ARGS??"").split(/\s+/).filter(Boolean);if(!args.length)log.warn("FACEBOOK_MCP_ARGS is empty; scans will create manual fallback tasks");
const transport=new StdioMcpTransport(command,args);const facebookSource=new FacebookMarketplaceAdapter(transport);const kijijiSource=process.env.APIFY_API_TOKEN?new ApifyKijijiAdapter(process.env.APIFY_API_TOKEN,process.env.KIJIJI_ACTOR_ID??"ivanvs~kijiji-scraper",Number(process.env.KIJIJI_MAX_RESULTS_PER_RUN??40),Number(process.env.KIJIJI_MAX_CHARGE_USD_PER_RUN??.25)):undefined;const sources=new Map<string,MarketplaceSource>([[facebookSource.type,facebookSource],...(kijijiSource?[[kijijiSource.type,kijijiSource] as [string,MarketplaceSource]]:[])]);const boss=new PgBoss({connectionString:queueDatabaseUrl,ssl:{rejectUnauthorized:false},schema:"marketplace_jobs",application_name:"marketplace-engine-worker"});
const crm=process.env.CRM_MODE==="webhook"&&process.env.CRM_WEBHOOK_URL?new WebhookCrmClient(process.env.CRM_WEBHOOK_URL,process.env.CRM_WEBHOOK_SECRET):new StubCrmClient();
const classifier=createListingClassifier({...(process.env.OPENAI_API_KEY?{apiKey:process.env.OPENAI_API_KEY}:{}),...(process.env.OPENAI_MODEL?{model:process.env.OPENAI_MODEL}:{})});
const SEARCH="source-search",DETAIL="listing-detail",DISPATCH="dispatch-due-searches",HEALTH="source-health",FOLLOWUPS="follow-up-eligibility",CRM_SYNC="crm-sync",EMAIL_DIGEST="email-opportunity-digest",DAILY_SUMMARY="email-daily-summary";
let sourceGate:Promise<void>=Promise.resolve(),nextSourceCallAt=0;
function callSource<T>(operation:()=>Promise<T>):Promise<T>{const run=sourceGate.then(async()=>{const wait=Math.max(0,nextSourceCallAt-Date.now());if(wait)await new Promise(resolve=>setTimeout(resolve,wait));nextSourceCallAt=Date.now()+21_000;return operation()});sourceGate=run.then(()=>undefined,()=>undefined);return run;}

async function executeSearch(id:string){
  const search=await prisma.searchDefinition.findUniqueOrThrow({where:{id},include:{cell:true,source:true,queryFamily:true,territory:{include:{region:{include:{launchConfiguration:true}}}}}});if(!search.enabled||!search.source.enabled||!search.territory.region.launchConfiguration?.marketplaceDiscoveryEnabled)return;
  const bucket=Math.floor(Date.now()/(search.searchFrequencyMinutes*60_000)),lockKey=`${id}:${bucket}`;const run=await prisma.searchRun.create({data:{searchDefinitionId:id,cellId:search.cellId,status:"RUNNING",lockKey}}).catch(()=>null);if(!run){log.info({searchDefinitionId:id},"overlapping search skipped");return;}
  try{const adapter=sources.get(search.source.type);if(!adapter)throw new Error(`${search.source.type} adapter is not configured`);const listings=[];const terms=Array.isArray(search.queryFamily.terms)?search.queryFamily.terms.filter((term):term is string=>typeof term==="string"):[];const query=terms.length?terms[bucket%terms.length]!:search.query;const filters={...(search.minimumPrice?{minPrice:Number(search.minimumPrice)}:{}),...(search.maximumPrice?{maxPrice:Number(search.maximumPrice)}:{}),...(search.category?{category:search.category}:{})};
    if(search.source.type==="facebook_marketplace"){for(const point of toFacebookSearchPoints({...search.cell,regionKey:search.territory.region.key as RegionKey,enabled:search.cell.enabled},Number(process.env.FACEBOOK_MAX_RADIUS_KM??100))){const result=await callSource(()=>adapter.searchListings({query,point,...filters}));listings.push(...result)}}
    else if(search.source.type==="kijiji"){const region=search.territory.region,latitude=(region.south+region.north)/2,longitude=(region.west+region.east)/2,corners=[[region.south,region.west],[region.south,region.east],[region.north,region.west],[region.north,region.east]] as const,radiusKm=Math.ceil(Math.max(...corners.map(([lat,lng])=>haversineKm({latitude,longitude},{latitude:lat,longitude:lng})))*1.1),incrementalLimit=Number(process.env.KIJIJI_INCREMENTAL_MAX_RESULTS??15),bootstrapLimit=Number(process.env.KIJIJI_MAX_RESULTS_PER_RUN??40),limit=search.lastRunAt?incrementalLimit:bootstrapLimit,overlapMs=Number(process.env.KIJIJI_INCREMENTAL_OVERLAP_MINUTES??60)*60_000,cutoff=search.lastRunAt?new Date(search.lastRunAt.getTime()-overlapMs):new Date(Date.now()-7*86400000);const result=await adapter.searchListings({query,point:{latitude,longitude,radiusKm,sourceCellKey:`${region.key}-region`,partIndex:0},limit,...filters});listings.push(...result.filter(item=>(item.publishedAt==null||item.publishedAt>=cutoff)&&(item.latitude==null||item.longitude==null||(item.latitude>=region.south&&item.latitude<=region.north&&item.longitude>=region.west&&item.longitude<=region.east))))}
    else throw new Error(`Unsupported source type: ${search.source.type}`);
    const needsDetail=search.source.type==="facebook_marketplace",summary=await ingestSearchResults(prisma,id,listings,{phone,classifier,deferClassification:needsDetail});if(needsDetail)for(const listing of listings)await boss.send(DETAIL,{searchDefinitionId:id,externalListingId:listing.externalListingId},{singletonKey:`${search.sourceId}:${listing.externalListingId}`,retryLimit:5,retryDelay:90,retryBackoff:true,retryDelayMax:3600,expireInSeconds:1800});const nextRunAt=new Date(Date.now()+search.searchFrequencyMinutes*60_000);await prisma.$transaction([prisma.searchRun.update({where:{id:run.id},data:{status:"COMPLETED",completedAt:new Date(),resultCount:summary.observed,newCount:summary.inserted,duplicateCount:summary.duplicates}}),prisma.searchDefinition.update({where:{id},data:{lastRunAt:new Date(),nextRunAt}}),prisma.source.update({where:{id:search.sourceId},data:{healthStatus:"HEALTHY",lastSuccessfulSync:new Date()}})]);log.info({source:search.source.type,searchDefinitionId:id,region:search.territory.region.key,query,detailJobs:needsDetail?listings.length:0,...summary},"search completed");}
  catch(error){const message=error instanceof Error?error.message:String(error),auth=/cookie|session|login|c_user|401|403/i.test(message),documents=/doc.?id|graphql|parse GraphQL/i.test(message);await prisma.$transaction([prisma.searchRun.update({where:{id:run.id},data:{status:"FAILED",completedAt:new Date(),errorCode:auth?"AUTH_REQUIRED":documents?"GRAPHQL_CHANGED":"SOURCE_ERROR",errorMessage:message.slice(0,1000)}}),prisma.source.update({where:{id:search.sourceId},data:{healthStatus:auth?"AUTH_REQUIRED":"DEGRADED",lastFailure:new Date()}}),...(documents?[prisma.searchDefinition.update({where:{id},data:{enabled:false}})]:[])]);if(auth||documents)await createManualSourceTask(prisma,id,auth?"Facebook session requires login":"Facebook GraphQL query identifiers must be refreshed; search paused");throw error;}
}

async function executeDetail(searchDefinitionId:string,externalListingId:string){const stored=await prisma.listing.findFirst({where:{externalListingId,source:{type:"facebook_marketplace"}},select:{rawSourcePayload:true}});const raw=stored?.rawSourcePayload&&typeof stored.rawSourcePayload==="object"&&!Array.isArray(stored.rawSourcePayload)?stored.rawSourcePayload as Record<string,unknown>:undefined;const fetchedAt=typeof raw?.detailFetchedAt==="string"?new Date(raw.detailFetchedAt):null;if(raw?.detailFetched===true&&fetchedAt&&!Number.isNaN(fetchedAt.getTime())&&Date.now()-fetchedAt.getTime()<24*60*60_000)return;const detail=await callSource(()=>facebookSource.getListing({externalListingId}));const detailRaw=detail.rawSourcePayload&&typeof detail.rawSourcePayload==="object"&&!Array.isArray(detail.rawSourcePayload)?detail.rawSourcePayload as Record<string,unknown>:{};const enriched={...detail,rawSourcePayload:{...detailRaw,detailFetched:true,detailFetchedAt:new Date().toISOString()}};const summary=await ingestSearchResults(prisma,searchDefinitionId,[enriched],{phone,classifier});log.info({searchDefinitionId,externalListingId,images:enriched.imageUrls.length,...summary},"listing detail classified");}

async function dispatchDue(){const regions=await prisma.region.findMany({where:{enabled:true,launchConfiguration:{marketplaceDiscoveryEnabled:true}},orderBy:{key:"asc"},select:{id:true,key:true}}),enabledSources=await prisma.source.findMany({where:{enabled:true},select:{id:true,type:true}}),due=[];for(const region of regions)for(const source of enabledSources){const search=await prisma.searchDefinition.findFirst({where:{enabled:true,sourceId:source.id,territory:{regionId:region.id},OR:[{nextRunAt:null},{nextRunAt:{lte:new Date()}}]},orderBy:[{priority:"desc"},{nextRunAt:"asc"},{id:"asc"}]});if(search)due.push({search,region:region.key,source:source.type})}for(const {search} of due)await boss.send(SEARCH,{searchDefinitionId:search.id},{singletonKey:search.id,retryLimit:4,retryDelay:60,retryBackoff:true,retryDelayMax:3600,expireInSeconds:1800});log.info({count:due.length,searches:due.map(item=>`${item.region}:${item.source}`)},"due searches dispatched")}
async function checkHealth(){for(const [type,adapter] of sources){const result=type==="facebook_marketplace"?await callSource(()=>adapter.healthCheck()):await adapter.healthCheck(),mapped=result.status==="healthy"?"HEALTHY":result.status==="auth_required"?"AUTH_REQUIRED":result.status==="degraded"?"DEGRADED":"UNAVAILABLE",source=await prisma.source.findUnique({where:{type}});if(!source)continue;await prisma.source.update({where:{id:source.id},data:{healthStatus:mapped,lastFailure:result.status==="healthy"?null:new Date()}});await prisma.auditEvent.create({data:{sourceId:source.id,eventType:"source_health",entityType:"Source",entityId:source.id,payload:{status:result.status,message:result.message??null}}});if(result.status!=="healthy")await sendSourceHealthAlert(prisma,{status:result.status,...(result.message?{message:`${source.name}: ${result.message}`}:{message:`${source.name} is ${result.status}`} )})}}
async function createFollowUps(){const initial=await prisma.outreachTask.findMany({where:{taskType:TaskType.INITIAL_OUTREACH,status:TaskStatus.SENT,completedAt:{lte:new Date(Date.now()-7*86400000)},followUpEligibility:true},include:{opportunity:{include:{listing:true,territory:{include:{region:{include:{launchConfiguration:true}}}},contacts:true}}}});for(const task of initial){const o=task.opportunity,eligible=evaluateFollowUp({daysSinceInitial:task.completedAt?Math.floor((Date.now()-task.completedAt.getTime())/86400000):0,listingStatus:o.listing.status.toLowerCase(),replied:o.contacts.some(c=>Boolean(c.responseStatus)&&!["no_response","maybe_later"].includes(c.responseStatus??"")),negativeResponse:o.contacts.some(c=>/not_interested|wrong_person|spam|blocked/i.test(c.responseStatus??"")),skipped:false,suppressed:false,followUpCount:await prisma.outreachTask.count({where:{opportunityId:o.id,taskType:TaskType.FOLLOW_UP}}),followUpsEnabled:o.territory.region.launchConfiguration?.followUpsEnabled===true});if(eligible){const brandName=o.territory.region.launchConfiguration?.outreachBrandName??"Saturn Star Movers";await prisma.outreachTask.create({data:{opportunityId:o.id,taskType:TaskType.FOLLOW_UP,assignedRepId:task.assignedRepId,status:TaskStatus.READY,priority:o.opportunityScore,suggestedMessage:`Hi${o.listing.sellerDisplayName?` ${o.listing.sellerDisplayName.split(" ")[0]}`:""}, just checking in in case pickup, delivery, or moving help is still useful. I'm with ${brandName}—feel free to message me here and I can get you a quick quote.`.slice(0,400),dueAt:new Date(),conversationUrl:task.conversationUrl}}).catch(()=>undefined)}}}
async function syncCrm(){const leads=await prisma.lead.findMany({where:{crmSyncStatus:{in:["PENDING","FAILED"]}},include:{opportunity:{include:{listing:true,territory:true,contacts:true}},source:true},take:25});for(const lead of leads){if(!(await prisma.regionLaunchConfiguration.findFirst({where:{region:{territories:{some:{id:lead.opportunity.territoryId}}},crmPushEnabled:true}})))continue;const payload={source:lead.source.type,sourceListingId:lead.opportunity.listing.externalListingId,sourceListingUrl:lead.opportunity.listing.listingUrl,territoryId:lead.opportunity.territoryId,...(lead.opportunity.assignedRepId?{assignedRepId:lead.opportunity.assignedRepId}:{}),...(lead.name?{customerName:lead.name}:{}),...(lead.phone?{phone:lead.phone}:{}),...(lead.email?{email:lead.email}:{}),serviceType:lead.serviceType,...(lead.originCity?{originCity:lead.originCity}:{}),...(lead.destinationCity?{destinationCity:lead.destinationCity}:{}),...(lead.estimatedMoveDate?{estimatedMoveDate:lead.estimatedMoveDate.toISOString()}:{}),opportunityScore:lead.opportunity.opportunityScore,outreachHistory:lead.opportunity.contacts};try{const key=crmLeadIdempotencyKey(payload);const result=await crm.createLead(payload,key);await prisma.lead.update({where:{id:lead.id},data:{crmExternalId:result.externalId,crmSyncStatus:"SYNCED"}})}catch(error){await prisma.lead.update({where:{id:lead.id},data:{crmSyncStatus:"FAILED"}});log.error({leadId:lead.id,error},"CRM sync failed")}}}

async function main(){validateGeographySeeds();boss.on("error",error=>log.error({error},"job queue error"));await boss.start();for(const name of [SEARCH,DETAIL,DISPATCH,HEALTH,FOLLOWUPS,CRM_SYNC,EMAIL_DIGEST,DAILY_SUMMARY])await boss.createQueue(name);await boss.work<{searchDefinitionId:string}>(SEARCH,{batchSize:1,localConcurrency:1},async(jobs:Job<{searchDefinitionId:string}>[])=>executeSearch(jobs[0]!.data.searchDefinitionId));await boss.work<{searchDefinitionId:string;externalListingId:string}>(DETAIL,{batchSize:1,localConcurrency:1},async(jobs:Job<{searchDefinitionId:string;externalListingId:string}>[])=>executeDetail(jobs[0]!.data.searchDefinitionId,jobs[0]!.data.externalListingId));await boss.work(DISPATCH,async()=>dispatchDue());await boss.work(HEALTH,async()=>checkHealth());await boss.work(FOLLOWUPS,async()=>createFollowUps());await boss.work(CRM_SYNC,async()=>syncCrm());await boss.work(EMAIL_DIGEST,async()=>{const result=await sendOpportunityDigest(prisma);log.info(result,"opportunity email digest checked")});await boss.work(DAILY_SUMMARY,async()=>{const sent=await sendDailySummary(prisma);log.info({sent},"daily email summary checked")});await boss.schedule(DISPATCH,"*/5 * * * *");await boss.schedule(HEALTH,"15 * * * *");await boss.schedule(FOLLOWUPS,"10 9 * * *",{}, {tz:"America/Toronto"});await boss.schedule(CRM_SYNC,"*/10 * * * *");await boss.schedule(EMAIL_DIGEST,"20 * * * *",{}, {tz:"America/Toronto"});await boss.schedule(DAILY_SUMMARY,"5 8 * * *",{}, {tz:"America/Toronto"});await dispatchDue();log.info({autonomousMessaging:false,emailAlerts:Boolean(process.env.RESEND_API_KEY&&process.env.ALERT_EMAIL_TO),detailBeforeClassification:true},"marketplace worker started")}
async function shutdown(){transport.close();await boss.stop({graceful:true,timeout:30_000});await prisma.$disconnect();process.exit(0)}process.on("SIGINT",shutdown);process.on("SIGTERM",shutdown);main().catch(error=>{log.fatal({error},"worker failed to start");process.exitCode=1});
