import {Prisma,TaskStatus,TaskType,prisma} from "@marketplace-engine/database";
import {TaskCard,type QueueTask} from "./task-card";
import {OutreachFilters} from "./filter-form";
import {headers} from "next/headers";
export const dynamic="force-dynamic";

type QueueSearch={territory?:string;minScore?:string;type?:string;source?:string;phone?:string;arrived?:string;sort?:string;page?:string};
const opportunityTypes=["residential_move","furniture_delivery","appliance_delivery","rental_move","office_move","packing","junk_removal","labour_only","equipment_purchase","retail_delivery_partner"] as const;
const sourceTypes=["facebook_marketplace","kijiji"] as const;
const PAGE_SIZE=25;
function torontoDayStart(now:Date){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Toronto",year:"numeric",month:"numeric",day:"numeric",hour:"numeric",minute:"numeric",second:"numeric",hourCycle:"h23"}).formatToParts(now),value=(type:string)=>Number(parts.find(part=>part.type===type)?.value),localAsUtc=Date.UTC(value("year"),value("month")-1,value("day"),value("hour"),value("minute"),value("second")),offset=localAsUtc-now.getTime();return new Date(Date.UTC(value("year"),value("month")-1,value("day"))-offset)}

export default async function Queue({searchParams}:{searchParams:Promise<QueueSearch>}){
  const requestHeaders=await headers(),restricted=requestHeaders.get("x-marketplace-role")==="MARKETPLACE_REP",repEmail=requestHeaders.get("x-marketplace-user-email"),currentRep=repEmail?await prisma.user.findUnique({where:{email:repEmail},select:{id:true}}):null;
  const params=await searchParams,requestedMinimum=Number(params.minScore??70),minimumScore=Math.max(0,Math.min(100,Number.isFinite(requestedMinimum)?requestedMinimum:70)),opportunityType=opportunityTypes.find(type=>type===params.type),sourceType=sourceTypes.find(type=>type===params.source),phone=["available","missing"].includes(params.phone??"")?params.phone!:"",arrived=["today","yesterday","7days","all"].includes(params.arrived??"")?params.arrived!:"all",sort=["newest","oldest","score"].includes(params.sort??"")?params.sort!:"newest",page=Math.max(1,Math.floor(Number(params.page??1)||1)),skip=(page-1)*PAGE_SIZE;
  const listingFilter:Prisma.ListingWhereInput={...(sourceType?{source:{type:sourceType}}:{}),...(phone==="available"?{publicContactPhone:{not:null}}:phone==="missing"?{publicContactPhone:null}:{})};
  const opportunityFilter:Prisma.OutreachTaskWhereInput={opportunity:{opportunityScore:{gte:minimumScore},...(params.territory?{territoryId:params.territory}:{}),...(opportunityType?{opportunityType}:{}),...(Object.keys(listingFilter).length?{listing:listingFilter}:{})}};
  const now=new Date(),today=torontoDayStart(now),yesterday=new Date(today.getTime()-86400000),tomorrow=new Date(today.getTime()+86400000),sevenDaysAgo=new Date(today.getTime()-6*86400000),arrivalFilter:Prisma.OutreachTaskWhereInput=arrived==="today"?{createdAt:{gte:today,lt:tomorrow}}:arrived==="yesterday"?{createdAt:{gte:yesterday,lt:today}}:arrived==="7days"?{createdAt:{gte:sevenDaysAgo,lt:tomorrow}}:{},claimFilter:Prisma.OutreachTaskWhereInput=restricted&&currentRep?{OR:[{claimedById:null},{claimExpiresAt:{lt:now}},{claimedById:currentRep.id}]}:{};
  const readyWhere:Prisma.OutreachTaskWhereInput={AND:[opportunityFilter,arrivalFilter,claimFilter,{status:{in:[TaskStatus.READY,TaskStatus.SNOOZED]},OR:[{snoozedUntil:null},{snoozedUntil:{lte:now}}]}]},awaitingWhere:Prisma.OutreachTaskWhereInput={AND:[opportunityFilter,arrivalFilter,{status:TaskStatus.SENT,taskType:TaskType.INITIAL_OUTREACH,result:null}]};
  const select={id:true,createdAt:true,finalMessage:true,suggestedMessage:true,conversationUrl:true,taskType:true,status:true,claimedById:true,claimExpiresAt:true,proofs:{orderBy:{createdAt:"desc" as const},take:1,select:{id:true}},opportunity:{select:{opportunityScore:true,scoreExplanation:true,listing:{select:{title:true,sellerDisplayName:true,locationText:true,listingUrl:true,publicContactPhone:true,source:{select:{type:true,name:true}}}},territory:{select:{primaryCity:true}},contacts:{orderBy:{sentAt:"desc" as const},take:3,select:{sentAt:true,responseStatus:true}}}}} satisfies Prisma.OutreachTaskSelect;
  const orderBy:Prisma.OutreachTaskOrderByWithRelationInput[]=sort==="score"?[{priority:"desc"},{createdAt:"desc"}]:sort==="oldest"?[{createdAt:"asc"}]:[{createdAt:"desc"}];
  const actorFilter=restricted&&currentRep?{actorId:currentRep.id}:{},[readyRows,awaitingRows,readyCount,awaitingCount,claimedCount,sentToday,skippedToday,arrivedToday,arrivedYesterday,territories]=await Promise.all([prisma.outreachTask.findMany({where:readyWhere,select,orderBy,skip,take:PAGE_SIZE}),prisma.outreachTask.findMany({where:awaitingWhere,select,orderBy,skip,take:PAGE_SIZE}),prisma.outreachTask.count({where:readyWhere}),prisma.outreachTask.count({where:awaitingWhere}),prisma.outreachTask.count({where:{AND:[opportunityFilter,{status:{in:[TaskStatus.READY,TaskStatus.SNOOZED]},claimedById:restricted&&currentRep?currentRep.id:{not:null},claimExpiresAt:{gt:now}}]}}),prisma.auditEvent.count({where:{eventType:"outreach_marked_sent",createdAt:{gte:today},...actorFilter}}),prisma.auditEvent.count({where:{eventType:"outreach_skipped",createdAt:{gte:today},...actorFilter}}),prisma.outreachTask.count({where:{AND:[opportunityFilter,{createdAt:{gte:today,lt:tomorrow}}]}}),prisma.outreachTask.count({where:{AND:[opportunityFilter,{createdAt:{gte:yesterday,lt:today}}]}}),prisma.territory.findMany({where:{enabled:true},orderBy:{name:"asc"},select:{id:true,name:true}})]);
  const mapTask=(row:typeof readyRows[number]):QueueTask=>({id:row.id,arrivedAt:row.createdAt.toISOString(),title:row.opportunity.listing.title,seller:row.opportunity.listing.sellerDisplayName??"Seller unavailable",city:row.opportunity.listing.locationText??row.opportunity.territory.primaryCity,score:row.opportunity.opportunityScore,message:row.finalMessage??row.suggestedMessage,url:row.opportunity.listing.listingUrl,conversationUrl:row.conversationUrl,sourceType:row.opportunity.listing.source.type,sourceName:row.opportunity.listing.source.name,publicPhone:row.opportunity.listing.publicContactPhone,proofId:row.proofs[0]?.id??null,claimedByMe:Boolean(currentRep&&row.claimedById===currentRep.id&&row.claimExpiresAt&&row.claimExpiresAt>now),explanation:Array.isArray(row.opportunity.scoreExplanation)?row.opportunity.scoreExplanation.filter((v):v is string=>typeof v==="string"):[],history:row.opportunity.contacts.map(c=>`${c.sentAt.toLocaleDateString("en-CA")}: ${c.responseStatus??"sent"}`),taskType:row.taskType,status:row.status});
  const ready=readyRows.map(mapTask),awaiting=awaitingRows.map(mapTask),totalPages=Math.max(1,Math.ceil(Math.max(readyCount,awaitingCount)/PAGE_SIZE));
  const pageHref=(target:number)=>{const query=new URLSearchParams();if(params.territory)query.set("territory",params.territory);query.set("minScore",String(minimumScore));if(opportunityType)query.set("type",opportunityType);if(sourceType)query.set("source",sourceType);if(phone)query.set("phone",phone);query.set("arrived",arrived);query.set("sort",sort);query.set("page",String(target));return `/outreach?${query}`};
  const metrics=[["Ready to send",readyCount,arrived==="all"?"Current backlog":"Matching date filter"],["Arrived today",arrivedToday,`Yesterday: ${arrivedYesterday}`],[restricted?"Claimed by you":"Claimed / in progress",claimedCount,"Active 30-minute claims"],[restricted?"Sent by you today":"Sent today",sentToday,"Toronto business day"],["Awaiting reply",awaitingCount,"Manual inbox check"],[restricted?"Skipped by you today":"Skipped today",skippedToday,"Reason recorded"]] as const;
  return <><header><div><p className="eyebrow">MANUAL OUTREACH</p><h1>Outreach workspace</h1><p>Live shared workload · Page {page} of {totalPages}. Every outbound message remains human-reviewed and manual.</p></div></header><section className="metrics outreachMetrics">{metrics.map(([label,value,note])=><article key={label}><small>{label}</small><strong>{value}</strong><span>{note}</span></article>)}</section><OutreachFilters territories={territories} territory={params.territory??""} minScore={String(minimumScore)} type={opportunityType??""} source={sourceType??""} phone={phone} arrived={arrived} sort={sort} opportunityTypes={opportunityTypes}/><h2>Ready to send and follow up</h2>{ready.length?ready.map(task=><TaskCard task={task} restricted={restricted} key={task.id}/>):<section className="panel empty"><span>★</span><h2>The send queue is clear</h2></section>}{!restricted&&<><h2 className="sectionTitle">Awaiting reply</h2>{awaiting.length?awaiting.map(task=><TaskCard task={task} key={task.id}/>):<section className="panel empty"><p>No conversations are awaiting an outcome.</p></section>}</>}<div className="actions">{page>1&&<a className="button" href={pageHref(page-1)}>← Previous</a>}{page<totalPages&&<a className="button" href={pageHref(page+1)}>Next →</a>}</div></>;
}
