import { classificationSchema, type Classification, type NormalizedListing } from "@marketplace-engine/shared";

export const DEFAULT_SCORING_WEIGHTS={explicitMoving:45,multipleLargeItems:20,recent:15,inTerritory:10,multipleSellerListings:10,urgentLanguage:8,commercialChange:45,rentalProperty:45,itemDelivery:25,largeItemSignal:20,highConfidence:10,activeListing:5,lowValueItem:-20,previousContact:-4,suspicious:-40,suppressed:-100,removed:-100} as const;
export interface ScoreContext { listing:NormalizedListing; classification:Classification; largeItemCount?:number; sellerListingCount?:number; inActiveTerritory:boolean; previousContactCount?:number; suspicious?:boolean; suppressed?:boolean; now?:Date }
export interface ScoreResult { score:number; explanation:string[] }
export function scoreOpportunity(context:ScoreContext,weights:Record<keyof typeof DEFAULT_SCORING_WEIGHTS,number>={...DEFAULT_SCORING_WEIGHTS}):ScoreResult {
  const lines:string[]=[];let score=0;const add=(points:number,label:string)=>{if(points===0)return;score+=points;lines.push(`${points>0?"+":""}${points} ${label}`)};
  if(context.classification.intentCategory==="explicit_moving")add(weights.explicitMoving,"Explicit moving language");
  if((context.largeItemCount??0)>=3)add(weights.multipleLargeItems,`${context.largeItemCount} large household items`);
  const age=context.listing.publishedAt?((context.now??new Date()).getTime()-context.listing.publishedAt.getTime())/86400000:Infinity;if(age<=1)add(weights.recent,"Posted within 24 hours");
  if(context.inActiveTerritory)add(weights.inTerritory,"Inside active territory");if((context.sellerListingCount??0)>=3)add(weights.multipleSellerListings,"Seller has multiple related listings");
  if(/must go|today|this week|asap|urgent/i.test(`${context.listing.title} ${context.listing.description??""}`))add(weights.urgentLanguage,"Urgency language");
  if(context.classification.intentCategory==="commercial_change")add(weights.commercialChange,"Commercial change signal");if(context.classification.intentCategory==="property_turnover")add(weights.rentalProperty,"Property turnover signal");
  if(context.classification.intentCategory==="item_delivery")add(weights.itemDelivery,"Delivery opportunity");if(["furniture_delivery","appliance_delivery","equipment_purchase"].includes(context.classification.opportunityType))add(weights.largeItemSignal,"Large-item truck or labour need");if(context.classification.confidence>=.7)add(weights.highConfidence,"High classification confidence");if(context.listing.status==="active")add(weights.activeListing,"Listing is active");
  if(context.classification.intentCategory==="weak_signal"&&(context.listing.price??Infinity)<50)add(weights.lowValueItem,"Low-value weak signal");if((context.previousContactCount??0)>0)add(weights.previousContact,"Previous contact attempt");
  if(context.suspicious)add(weights.suspicious,"Suspicious listing");if(context.suppressed)add(weights.suppressed,"Seller suppressed");if(context.listing.status==="removed"||context.listing.status==="sold")add(weights.removed,"Listing inactive");
  return {score:Math.max(0,Math.min(100,score)),explanation:lines};
}

export function classifyDeterministically(listing:NormalizedListing):Classification {
  const text=`${listing.title} ${listing.description??""}`.toLowerCase();
  const competitor=isCompetitorAdvertisement(listing), explicit=/moving sale|moving out|relocating|leaving province|everything must go/.test(text), urgent=/must go|need gone|today/.test(text), rental=/apartment for rent|house for rent|tenant/.test(text), commercial=/office closing|business closing|office furniture/.test(text), appliance=/washer|dryer|refrigerator|freezer|stove|appliance/.test(text), furniture=/sectional|couch|sofa|dining set|bedroom set|dresser|wardrobe|pool table/.test(text);
  const opportunityType=competitor?"competitor":explicit?"residential_move":rental?"rental_move":commercial?"office_move":appliance?"appliance_delivery":furniture?"furniture_delivery":"irrelevant";
  const intentCategory=competitor?"none":explicit?"explicit_moving":rental?"property_turnover":commercial?"commercial_change":appliance||furniture?"item_delivery":"none";
  return classificationSchema.parse({opportunityType,intentCategory,confidence:explicit?0.92:rental||commercial||competitor?0.82:appliance||furniture?0.72:0.9,urgency:urgent?90:explicit?70:40,estimatedJobSize:explicit||commercial?"large":appliance||furniture?"small":"unknown",positiveSignals:[explicit&&"Explicit moving language",urgent&&"Urgency language",rental&&"Rental turnover",commercial&&"Commercial change",appliance&&"Large appliance",furniture&&"Large furniture"].filter((v):v is string=>Boolean(v)),negativeSignals:competitor?["Competing moving-service advertisement"]:opportunityType==="irrelevant"?["No relevant service signal"]:[],recommendedAction:competitor||opportunityType==="irrelevant"?"skip":explicit&&urgent?"contact_now":"contact_later",reasoningSummary:competitor?"This is a moving-service advertisement and must not receive outreach.":opportunityType==="irrelevant"?"No moving, delivery, rental, or commercial-change signal was detected.":`Detected a ${intentCategory.replaceAll("_"," ")} signal relevant to ${opportunityType.replaceAll("_"," ")}.`});
}

export function isCompetitorAdvertisement(listing:NormalizedListing){const title=listing.title.toLowerCase(),text=`${listing.title} ${listing.description??""}`.toLowerCase();const service=/\b(moving company|professional movers?|local movers?|moving services?|residential (?:and|&) commercial moving|licensed movers?|insured movers?|movers available|moving truck and (?:two|2) men)\b/.test(text);const titleAdvert=/\b(movers?|moving services?|moving company)\b/.test(title)&&!/\b(need|needed|looking for|recommend|wanted|seeking)\b/.test(title);const sales=/\b(free estimates?|call (?:or )?text|book (?:now|today)|hourly rates?|starting at \$|we offer|our services?)\b/.test(text);const moveSale=/\b(moving sale|moving out|must go|everything must go)\b/.test(text);return !moveSale&&(titleAdvert||(service&&sales))}

const classificationJsonSchema={type:"object",additionalProperties:false,properties:{opportunityType:{type:"string",enum:["residential_move","furniture_delivery","appliance_delivery","rental_move","office_move","packing","junk_removal","labour_only","equipment_purchase","competitor","irrelevant"]},intentCategory:{type:"string",enum:["explicit_moving","likely_moving","item_delivery","property_turnover","commercial_change","weak_signal","none"]},confidence:{type:"number",minimum:0,maximum:1},urgency:{type:"number",minimum:0,maximum:100},estimatedJobSize:{type:"string",enum:["small","medium","large","unknown"]},positiveSignals:{type:"array",items:{type:"string"},maxItems:20},negativeSignals:{type:"array",items:{type:"string"},maxItems:20},recommendedAction:{type:"string",enum:["contact_now","contact_later","monitor","skip"]},reasoningSummary:{type:"string",maxLength:600}},required:["opportunityType","intentCategory","confidence","urgency","estimatedJobSize","positiveSignals","negativeSignals","recommendedAction","reasoningSummary"]} as const;
export class OpenAiListingClassifier {constructor(private readonly apiKey:string,private readonly model="gpt-5.6-luna"){}async classify(listing:NormalizedListing):Promise<Classification>{const listingText=JSON.stringify({title:listing.title,description:listing.description??null,price:listing.price??null,category:listing.category??null,condition:listing.condition??null,location:listing.locationText??null,status:listing.status,publishedAt:listing.publishedAt?.toISOString()??null});const content:Array<Record<string,unknown>>=[{type:"input_text",text:listingText},...listing.imageUrls.slice(0,3).map(imageUrl=>({type:"input_image",image_url:imageUrl,detail:"low"}))];const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"authorization":`Bearer ${this.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:this.model,input:[{role:"system",content:"Classify Marketplace listings for a Canadian moving and delivery company. Evaluate text, category, timing, location, and photos together. For rental or sale property listings, the advertiser may be a landlord, property manager, or seller who can refer the incoming tenant or buyer. An empty or vacant unit is a positive property-turnover signal because an inbound move may be imminent; never downgrade a rental merely because no furniture is visible. Furnished rooms may add furniture-handling demand. Use photos to identify large items, whole-room contents, appliances, vacancy or occupancy turnover, unsafe content, and suspicious text-image mismatches. Competitor moving-service advertisements and irrelevant content must be skipped. Return only the required schema."},{role:"user",content}],text:{format:{type:"json_schema",name:"marketplace_classification",strict:true,schema:classificationJsonSchema}}})});if(!response.ok)throw new Error(`OpenAI classification failed: ${response.status}`);const data=await response.json() as {output?:Array<{content?:Array<{type?:string;text?:string}>}>};const output=data.output?.flatMap(item=>item.content??[]).find(item=>item.type==="output_text")?.text;if(!output)throw new Error("OpenAI classification returned no structured output");return classificationSchema.parse(JSON.parse(output))}}
export function createListingClassifier(options:{apiKey?:string;model?:string}){if(!options.apiKey)return classifyDeterministically;const ai=new OpenAiListingClassifier(options.apiKey,options.model);return async(listing:NormalizedListing)=>{if(isCompetitorAdvertisement(listing))return classifyDeterministically(listing);try{return await ai.classify(listing)}catch{return classifyDeterministically(listing)}}}

export function draftMessage(listing:NormalizedListing,classification:Classification,phone:string):string {
  const name=listing.sellerDisplayName?` ${listing.sellerDisplayName.trim().split(/\s+/)[0]}`:"";const digits=phone.replace(/\D/g,"");const displayPhone=digits.length===10?`(${digits.slice(0,3)}) ${digits.slice(3,6)}-${digits.slice(6)}`:phone;const text=`${listing.title} ${listing.description??""}`.toLowerCase();
  const item=/\b(sectional|couch|sofa|dining (?:table|set)|bedroom set|bed frame|mattress|dresser|wardrobe|desk|patio set|pool table|washer(?: and)? dryer|washer|dryer|refrigerator|fridge|freezer|stove|appliance|cabinet|bookshelf)\b/i.exec(text)?.[0]??"item";
  let body:string;
  switch(classification.opportunityType){
    case "residential_move":body="It looks like you're preparing for a move. If you need a hand with the larger items or the final move, our Saturn Star moving team would be happy to help.";break;
    case "rental_move":body=`It looks like you're renting out a place${listing.locationText?` in ${listing.locationText.split(",")[0]}`:""}. If your new tenant needs help moving in, our Saturn Star team can help with the move or furniture delivery.`;break;
    case "office_move":body="It looks like you're clearing out some business items. If any buyers need pickup or delivery—or you need help with the final clear-out—our Saturn Star moving team can help.";break;
    case "appliance_delivery":body=`That ${item.toLowerCase()} may need a truck once it sells. If your buyer needs pickup and delivery, our Saturn Star team can take care of it locally.`;break;
    case "furniture_delivery":case "equipment_purchase":body=`That ${item.toLowerCase()} looks like something a buyer may need help moving. If delivery comes up, our Saturn Star team can pick it up and deliver it locally.`;break;
    case "packing":body="If packing becomes one more thing on your list, our Saturn Star moving team can help make it easier.";break;
    case "junk_removal":body="If you need help clearing out the remaining items, our Saturn Star team can handle the heavy lifting and removal.";break;
    case "labour_only":body="If you need an extra set of hands for the heavy items, our Saturn Star moving team can help with the loading and lifting.";break;
    default:body="If moving, pickup, or delivery help comes up, our Saturn Star moving team would be happy to help.";
  }
  return `Hi${name}, ${body} Feel free to message me here, or call or text ${displayPhone}, and we can give you a quick quote.`.slice(0,400);
}
