import {z} from "zod";
import {normalizedListingSchema,type NormalizedListing} from "@marketplace-engine/shared";
import type {MarketplaceSource,SearchListingsInput,SourceHealth} from "./index.js";

const sellerSchema=z.object({id:z.union([z.string(),z.number()]).optional(),name:z.string().optional(),sellerType:z.string().optional(),userType:z.string().optional(),phoneNumber:z.string().nullable().optional(),profilePath:z.string().optional(),url:z.string().url().optional(),numberOfListings:z.number().optional(),verified:z.boolean().optional()}).passthrough();
const locationSchema=z.object({latitude:z.number().optional(),longitude:z.number().optional(),name:z.string().optional(),street_address:z.string().optional(),locality:z.string().nullable().optional(),region:z.string().nullable().optional(),country:z.string().nullable().optional()}).passthrough();
export const kijijiActorListingSchema=z.object({url:z.string().url(),title:z.string().default(""),description:z.string().optional().default(""),price:z.union([z.string(),z.number()]).nullable().optional(),currency:z.string().nullable().optional(),condition:z.string().nullable().optional(),images:z.array(z.union([z.string().url(),z.object({url:z.string().url()}).passthrough()])).optional().default([]),address:locationSchema.optional(),seller:sellerSchema.optional(),dateFrom:z.union([z.string(),z.date()]).nullable().optional(),dateTo:z.union([z.string(),z.date()]).nullable().optional(),attributes:z.unknown().optional(),features:z.unknown().optional()}).passthrough();
export type KijijiActorListing=z.infer<typeof kijijiActorListingSchema>;

const parsePrice=(value:unknown)=>{if(typeof value==="number"&&value>=0)return value;if(typeof value!=="string")return undefined;const parsed=Number(value.replace(/[^0-9.-]/g,""));return Number.isFinite(parsed)&&parsed>=0?parsed:undefined};
export function extractKijijiListingId(url:string){const match=new URL(url).pathname.match(/\/(\d+)(?:\/)?$/);if(!match)throw new Error(`Kijiji listing URL has no stable ad ID: ${url}`);return match[1]!}
export function extractPublicPhone(raw:unknown){const parsed=kijijiActorListingSchema.safeParse(raw);if(!parsed.success)return undefined;const direct=parsed.data.seller?.phoneNumber;if(direct&&/\d{10}/.test(direct.replace(/\D/g,""))&&!/x/i.test(direct))return direct;const matches=parsed.data.description.match(/(?:\+?1[\s.-]?)?\(?([2-9]\d{2})\)?[\s.-]?(\d{3})[\s.-]?(\d{4})/);return matches?`${matches[1]}-${matches[2]}-${matches[3]}`:undefined}
export function normalizeKijijiListing(input:unknown):NormalizedListing {const raw=kijijiActorListingSchema.parse(input),id=extractKijijiListingId(raw.url),location=raw.address,imageUrls=raw.images.map(image=>typeof image==="string"?image:image.url),publishedAt=raw.dateFrom?new Date(raw.dateFrom):undefined,publicContactPhone=extractPublicPhone(raw);return normalizedListingSchema.parse({sourceType:"kijiji",externalListingId:id,listingUrl:raw.url,sellerExternalId:raw.seller?.id==null?undefined:String(raw.seller.id),sellerDisplayName:raw.seller?.name,title:raw.title,description:raw.description||undefined,price:parsePrice(raw.price),currency:raw.currency??"CAD",condition:raw.condition??undefined,locationText:location?.street_address??location?.name??location?.locality??undefined,latitude:location?.latitude,longitude:location?.longitude,imageUrls,publicContactPhone,publishedAt:publishedAt&&!Number.isNaN(publishedAt.getTime())?publishedAt:undefined,status:"active",rawSourcePayload:{...raw,publicContactPhone,detailFetched:true,detailFetchedAt:new Date().toISOString()}})}

const slug=(value:string)=>value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export function buildKijijiSearchUrl(input:SearchListingsInput){const query=slug(input.query);const params=new URLSearchParams({dc:"true",ll:`${input.point.latitude},${input.point.longitude}`,radius:String(Math.ceil(input.point.radiusKm)),sort:"dateDesc"});return `https://www.kijiji.ca/b-canada/${query}/k0l0?${params}`}

export class ApifyKijijiAdapter implements MarketplaceSource {
  readonly type="kijiji";
  constructor(private readonly token:string,private readonly actorId="ivanvs~kijiji-scraper",private readonly maxResults=40,private readonly maxChargeUsd=.25){}
  async searchListings(input:SearchListingsInput){const response=await fetch(`https://api.apify.com/v2/acts/${this.actorId}/run-sync-get-dataset-items?clean=true&format=json&maxTotalChargeUsd=${this.maxChargeUsd}`,{method:"POST",headers:{authorization:`Bearer ${this.token}`,"content-type":"application/json"},body:JSON.stringify({urls:[{url:buildKijijiSearchUrl(input)}],maxRecords:Math.min(input.limit??this.maxResults,this.maxResults)})});if(!response.ok)throw new Error(`Apify Kijiji run failed: ${response.status} ${(await response.text()).slice(0,300)}`);const payload=await response.json();if(!Array.isArray(payload))throw new Error("Apify Kijiji actor returned a non-array dataset");return payload.map(normalizeKijijiListing)}
  async getListing():Promise<NormalizedListing>{throw new Error("Kijiji search results already include full listing details")}
  async healthCheck():Promise<SourceHealth>{try{const response=await fetch(`https://api.apify.com/v2/acts/${this.actorId}`,{headers:{authorization:`Bearer ${this.token}`}});if(!response.ok)throw new Error(`Apify actor health returned ${response.status}`);return {status:"healthy",checkedAt:new Date()}}catch(error){return {status:"unavailable",message:error instanceof Error?error.message:String(error),checkedAt:new Date()}}}
}
