import { describe,expect,it } from "vitest";
import { cityAliasSeeds,citySeeds,citiesByRegion,generateAllCells,generateRegionCells,haversineKm,matchCity,regionSeeds,toFacebookSearchPoints,validateGeographySeeds } from "../src/index.js";

describe("canonical geography seeds",()=>{
  it("has exact counts and validates",()=>{expect(()=>validateGeographySeeds()).not.toThrow();expect(regionSeeds).toHaveLength(7);expect(citySeeds).toHaveLength(171);expect(cityAliasSeeds).toHaveLength(6);expect(generateAllCells(regionSeeds)).toHaveLength(55);expect(Object.fromEntries(Object.entries(citiesByRegion).map(([k,v])=>[k,v.length]))).toEqual({windsor:22,chatham:22,sarnia:27,london:39,woodstock:23,wkg:28,ottawa:10})});
  it("resolves exact canonical names and aliases without substrings",()=>{expect(matchCity("  MITCHELL’S   BAY ")?.canonicalName).toBe("Mitchell's Bay");expect(matchCity("Chatham-Kent")?.canonicalName).toBe("Chatham Kent");expect(matchCity("East Harrow")?.regionKey).toBe("windsor");expect(matchCity("London town")).toBeNull()});
});
describe("grid generation",()=>{
  it("covers bounds without gaps and uses south-to-north rows",()=>{for(const region of regionSeeds){const cells=generateRegionCells(region);expect(cells).toHaveLength(region.grid.expectedCellCount);for(const cell of cells){expect(cell.east).toBeGreaterThan(cell.west);expect(cell.north).toBeGreaterThan(cell.south);expect(cell.widthKm).toBeGreaterThan(0);expect(cell.heightKm).toBeGreaterThan(0);expect(cell.centerLongitude).toBeCloseTo((cell.west+cell.east)/2,10);expect(cell.centerLatitude).toBeCloseTo((cell.south+cell.north)/2,10)}for(let r=0;r<region.grid.rows;r++)for(let c=0;c<region.grid.columns;c++){const cell=cells.find(x=>x.rowIndex===r&&x.columnIndex===c)!;expect(cell.west).toBe(region.grid.longitudeBreakpoints[c]);expect(cell.east).toBe(region.grid.longitudeBreakpoints[c+1]);expect(cell.south).toBe(region.grid.latitudeBreakpoints[r]);expect(cell.north).toBe(region.grid.latitudeBreakpoints[r+1])}}});
  it("uses plausible geospatial distances and valid Facebook inputs",()=>{expect(haversineKm({latitude:42.3,longitude:-83},{latitude:42.3,longitude:-82})).toBeGreaterThan(80);const windsor=generateRegionCells(regionSeeds[0]!);for(const cell of windsor){expect(cell.facebookRadiusKm).toBeGreaterThan(10);expect(cell.facebookRadiusKm).toBeLessThan(30);const points=toFacebookSearchPoints(cell,100);expect(points).toHaveLength(1);expect(points[0]!.radiusKm).toBe(cell.facebookRadiusKm)}});
  it("subdivides for source radius limits without changing canonical cells",()=>{const cell=generateRegionCells(regionSeeds[0]!)[0]!;const points=toFacebookSearchPoints(cell,5);expect(points.length).toBeGreaterThan(1);expect(points.every(p=>p.radiusKm<=5)).toBe(true)});
});
