import { ListingStatus, Prisma, PrismaClient, TaskStatus, TaskType } from "@prisma/client";
import { classifyDeterministically, DEFAULT_SCORING_WEIGHTS, draftMessage, scoreOpportunity } from "@marketplace-engine/intelligence";
import { evaluateInitialOutreach, isLocationExcluded } from "@marketplace-engine/operations";
import { stableListingHash, type Classification, type NormalizedListing } from "@marketplace-engine/shared";

const json=(value:unknown)=>JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
const statusMap={active:ListingStatus.ACTIVE,pending:ListingStatus.PENDING,sold:ListingStatus.SOLD,removed:ListingStatus.REMOVED,unknown:ListingStatus.UNKNOWN} as const;
export interface IngestionSummary {observed:number;inserted:number;materiallyChanged:number;duplicates:number;opportunities:number;tasks:number;skipped:number}
export interface PipelineOptions {phone:string;classifier?:(listing:NormalizedListing)=>Promise<Classification>|Classification;now?:Date}

export async function ingestSearchResults(db:PrismaClient,searchDefinitionId:string,inputListings:readonly NormalizedListing[],options:PipelineOptions):Promise<IngestionSummary>{
  const now=options.now??new Date(),classifier=options.classifier??classifyDeterministically;
  const search=await db.searchDefinition.findUniqueOrThrow({where:{id:searchDefinitionId},include:{source:true,territory:{include:{region:{include:{launchConfiguration:true}}}},cell:true}});
  const scoringConfig=await db.scoringConfiguration.findFirst({where:{enabled:true},orderBy:{version:"desc"}});const weights:Record<keyof typeof DEFAULT_SCORING_WEIGHTS,number>={...DEFAULT_SCORING_WEIGHTS};if(scoringConfig?.weights&&typeof scoringConfig.weights==="object"&&!Array.isArray(scoringConfig.weights))for(const key of Object.keys(weights) as Array<keyof typeof weights>){const value=(scoringConfig.weights as Record<string,unknown>)[key];if(typeof value==="number"&&Number.isFinite(value))weights[key]=value;}
  const sourceConfiguration=search.source.configuration&&typeof search.source.configuration==="object"&&!Array.isArray(search.source.configuration)?search.source.configuration as Record<string,unknown>:{};const excludedLocationTerms=Array.isArray(sourceConfiguration.excludedLocationTerms)?sourceConfiguration.excludedLocationTerms.filter((term):term is string=>typeof term==="string"):[];const maxListingAgeDays=typeof sourceConfiguration.maxListingAgeDays==="number"?sourceConfiguration.maxListingAgeDays:7;const includeUnknownAge=sourceConfiguration.includeListingsWithUnknownAge!==false;
  const summary:IngestionSummary={observed:inputListings.length,inserted:0,materiallyChanged:0,duplicates:0,opportunities:0,tasks:0,skipped:0};
  const unique=new Map(inputListings.map((item)=>[`${item.sourceType}:${item.externalListingId}`,item]));summary.duplicates=inputListings.length-unique.size;
  for(const listing of unique.values()){
    const listingAgeDays=listing.publishedAt?(now.getTime()-listing.publishedAt.getTime())/86400000:null;if(isLocationExcluded(listing.locationText,excludedLocationTerms)||(listingAgeDays!=null&&listingAgeDays>maxListingAgeDays)||(listingAgeDays==null&&!includeUnknownAge)){summary.skipped++;continue;}
    const hash=stableListingHash(listing),existing=await db.listing.findUnique({where:{sourceId_externalListingId:{sourceId:search.sourceId,externalListingId:listing.externalListingId}}});
    let sellerId:string|undefined;
    if(listing.sellerExternalId){const seller=await db.sellerProfile.upsert({where:{sourceId_externalSellerId:{sourceId:search.sourceId,externalSellerId:listing.sellerExternalId}},update:{displayName:listing.sellerDisplayName??null,lastObservedAt:now},create:{sourceId:search.sourceId,externalSellerId:listing.sellerExternalId,displayName:listing.sellerDisplayName??null,lastObservedAt:now,territoriesObserved:json([search.territoryId])}});sellerId=seller.id;}
    const values={listingUrl:listing.listingUrl,sellerId:sellerId??null,sellerDisplayName:listing.sellerDisplayName??null,title:listing.title,description:listing.description??null,price:listing.price!=null?new Prisma.Decimal(listing.price):null,currency:listing.currency,category:listing.category??null,condition:listing.condition??null,locationText:listing.locationText??null,latitude:listing.latitude??null,longitude:listing.longitude??null,imageUrls:json(listing.imageUrls),publishedAt:listing.publishedAt??null,lastObservedAt:now,status:statusMap[listing.status],contentHash:hash,rawSourcePayload:json(listing.rawSourcePayload)};
    const materiallyChanged=Boolean(existing&&existing.contentHash!==hash);if(existing&&!materiallyChanged){await db.listing.update({where:{id:existing.id},data:{lastObservedAt:now,status:statusMap[listing.status],rawSourcePayload:json(listing.rawSourcePayload)}});summary.duplicates++;continue;}
    const stored=existing?await db.listing.update({where:{id:existing.id},data:{...values,materialVersion:{increment:1}}}):await db.listing.create({data:{sourceId:search.sourceId,externalListingId:listing.externalListingId,firstObservedAt:now,...values}});if(existing)summary.materiallyChanged++;else summary.inserted++;
    const classification=await classifier(listing);const previousContactCount=sellerId?await db.contactAttempt.count({where:{sellerId}}):0;const suppressed=Boolean(sellerId&&await db.suppressionRecord.findFirst({where:{sellerId,OR:[{permanent:true},{expiresAt:{gt:now}}]}}));
    const score=scoreOpportunity({listing,classification,inActiveTerritory:search.territory.region.launchConfiguration?.outreachEnabled===true,previousContactCount,suppressed,now},weights);
    const opportunity=await db.opportunity.upsert({where:{listingId_territoryId:{listingId:stored.id,territoryId:search.territoryId}},update:{opportunityType:classification.opportunityType,intentCategory:classification.intentCategory,confidence:classification.confidence,opportunityScore:score.score,urgencyScore:classification.urgency,estimatedServiceType:classification.opportunityType,estimatedJobSize:classification.estimatedJobSize,reasoningSummary:classification.reasoningSummary,positiveSignals:json(classification.positiveSignals),negativeSignals:json(classification.negativeSignals),scoreExplanation:json(score.explanation),recommendedAction:classification.recommendedAction},create:{listingId:stored.id,territoryId:search.territoryId,assignedRepId:search.territory.assignedRepId,opportunityType:classification.opportunityType,intentCategory:classification.intentCategory,confidence:classification.confidence,opportunityScore:score.score,urgencyScore:classification.urgency,estimatedServiceType:classification.opportunityType,estimatedJobSize:classification.estimatedJobSize,reasoningSummary:classification.reasoningSummary,positiveSignals:json(classification.positiveSignals),negativeSignals:json(classification.negativeSignals),scoreExplanation:json(score.explanation),recommendedAction:classification.recommendedAction}});summary.opportunities++;
    const activeTask=await db.outreachTask.findFirst({where:{opportunityId:opportunity.id,status:{in:[TaskStatus.READY,TaskStatus.SNOOZED]}}});const seller= sellerId?await db.sellerProfile.findUnique({where:{id:sellerId}}):null;const normalizedSellerName=listing.sellerDisplayName?.trim().replace(/\s+/g," ");const sellerListingScope=sellerId?{sellerId}:{sourceId:search.sourceId,...(normalizedSellerName?{sellerDisplayName:{equals:normalizedSellerName,mode:Prisma.QueryMode.insensitive}}:{id:stored.id})};const activeSellerTask=await db.outreachTask.findFirst({where:{status:{in:[TaskStatus.READY,TaskStatus.SNOOZED]},opportunity:{listing:sellerListingScope},NOT:{opportunityId:opportunity.id}}});const recentNamedContact=!sellerId&&normalizedSellerName?await db.contactAttempt.findFirst({where:{sentAt:{gte:new Date(now.getTime()-30*86400000)},opportunity:{listing:{sourceId:search.sourceId,sellerDisplayName:{equals:normalizedSellerName,mode:Prisma.QueryMode.insensitive}}}},orderBy:{sentAt:"desc"}}):null;const launch=search.territory.region.launchConfiguration;
    const eligibility=evaluateInitialOutreach({listingStatus:listing.status,score:score.score,minimumScore:launch?.minimumOpportunityScore??70,outreachEnabled:launch?.outreachEnabled===true,sellerSuppressed:suppressed||seller?.suppressionStatus===true,listingSuppressed:Boolean(await db.suppressionRecord.findFirst({where:{listingId:stored.id,OR:[{permanent:true},{expiresAt:{gt:now}}]}})),activeTaskExists:Boolean(activeTask||activeSellerTask),...(seller?.lastOutreachAt?{sellerLastContactAt:seller.lastOutreachAt}:recentNamedContact?.sentAt?{sellerLastContactAt:recentNamedContact.sentAt}:{}),sellerContactCount:seller?.previousOutreachCount??(recentNamedContact?1:0),maxContactAttempts:2,now});
    const startOfDay=new Date(now);startOfDay.setUTCHours(0,0,0,0);const tasksToday=await db.outreachTask.count({where:{opportunity:{territoryId:search.territoryId},createdAt:{gte:startOfDay}}});const underDailyLimit=launch?.dailyTaskLimit==null||tasksToday<launch.dailyTaskLimit;
    if(eligibility.allowed&&underDailyLimit&&classification.recommendedAction!=="skip"){await db.outreachTask.create({data:{opportunityId:opportunity.id,taskType:TaskType.INITIAL_OUTREACH,assignedRepId:search.territory.assignedRepId,status:TaskStatus.READY,priority:score.score,suggestedMessage:draftMessage(listing,classification,options.phone),dueAt:now,followUpEligibility:true}});summary.tasks++;}else summary.skipped++;
    await db.auditEvent.create({data:{sourceId:search.sourceId,eventType:"opportunity_scored",entityType:"Opportunity",entityId:opportunity.id,payload:json({score:score.score,eligibility})}});
  }
  return summary;
}

export async function createManualSourceTask(db:PrismaClient,searchDefinitionId:string,reason:string){const search=await db.searchDefinition.findUniqueOrThrow({where:{id:searchDefinitionId}});const listing=await db.listing.upsert({where:{sourceId_externalListingId:{sourceId:search.sourceId,externalListingId:`manual:${searchDefinitionId}`}},update:{lastObservedAt:new Date()},create:{sourceId:search.sourceId,externalListingId:`manual:${searchDefinitionId}`,listingUrl:"https://www.facebook.com/marketplace/",title:"Manual Marketplace action required",currency:"CAD",status:ListingStatus.UNKNOWN,contentHash:`manual:${searchDefinitionId}`,rawSourcePayload:{reason}}});const opportunity=await db.opportunity.upsert({where:{listingId_territoryId:{listingId:listing.id,territoryId:search.territoryId}},update:{reasoningSummary:reason},create:{listingId:listing.id,territoryId:search.territoryId,opportunityType:"irrelevant",intentCategory:"none",confidence:1,opportunityScore:0,urgencyScore:100,estimatedServiceType:"manual_source_action",estimatedJobSize:"unknown",reasoningSummary:reason,positiveSignals:[],negativeSignals:[reason],scoreExplanation:[],recommendedAction:"monitor"}});return db.outreachTask.upsert({where:{opportunityId_taskType_status:{opportunityId:opportunity.id,taskType:TaskType.MANUAL_SOURCE_ACTION,status:TaskStatus.READY}},update:{suggestedMessage:reason,dueAt:new Date()},create:{opportunityId:opportunity.id,taskType:TaskType.MANUAL_SOURCE_ACTION,status:TaskStatus.READY,priority:100,suggestedMessage:reason,dueAt:new Date()}})}
