import {prisma} from "@marketplace-engine/database";
import {captureFacebookGroupPost,createFacebookGroup,generateFacebookGroupContentDraft,reviewFacebookGroupPost,toggleFacebookGroup,updateFacebookGroupAdminOutreach,updateFacebookGroupContentDraft,updateFacebookGroupPlaybook} from "./actions";
export const dynamic="force-dynamic";

const signalLabel:Record<string,string>={direct_request:"Direct request",moving_signal:"Moving signal",property_referral:"Property referral",heavy_item:"Heavy item",competitor:"Competitor",irrelevant:"Irrelevant"};
const assessmentStatus=(value:unknown)=>typeof value==="object"&&value&&"status" in value?String(value.status):"not reviewed";

export default async function FacebookGroups(){
  const [regions,groups,posts,drafts]=await Promise.all([
    prisma.region.findMany({where:{enabled:true},orderBy:{name:"asc"}}),
    prisma.facebookGroup.findMany({include:{region:true,admins:true,_count:{select:{posts:true,contentDrafts:true}}},orderBy:[{enabled:"desc"},{searchPriority:"desc"},{name:"asc"}]}),
    prisma.facebookGroupPost.findMany({include:{group:{include:{region:true}}},orderBy:[{reviewStatus:"asc"},{opportunityScore:"desc"},{firstCapturedAt:"desc"}],take:100}),
    prisma.facebookGroupContentDraft.findMany({include:{group:{include:{region:true}}},where:{status:{in:["DRAFT","APPROVED"]}},orderBy:[{scheduledFor:"asc"},{createdAt:"desc"}],take:100})
  ]);
  const active=groups.filter(group=>group.enabled),unreviewed=posts.filter(post=>post.reviewStatus==="UNREVIEWED"),direct=posts.filter(post=>post.opportunityType==="direct_request"&&post.reviewStatus==="UNREVIEWED");
  return <><header><div><p className="eyebrow">ATTACK + DEFENSE</p><h1>Facebook Groups</h1><p>Permission-aware community posting, opportunity radar, and administrator outreach. Every Facebook action remains human-reviewed and manual.</p></div></header>
    <section className="metrics"><article><small>Active groups</small><strong>{active.length}</strong></article><article><small>Posts to review</small><strong>{unreviewed.length}</strong></article><article><small>Direct requests</small><strong>{direct.length}</strong></article><article><small>Content drafts</small><strong>{drafts.length}</strong></article></section>

    <section className="panel"><h2>Today’s community posting queue</h2><p>Draft thoughtful, locally useful posts for groups whose rules permit participation. Open the group, review the wording, post manually, then record the Facebook URL.</p>
      {drafts.length===0?<p>No content drafts are waiting.</p>:<div className="cards">{drafts.map(draft=><article className="card" key={draft.id}><div className="cardTop"><div><small>{draft.group.name} · {draft.group.region.name}</small><h3>{draft.contentAngle.replaceAll("_"," ")}</h3></div><b>{draft.status}</b></div><form action={updateFacebookGroupContentDraft}><input type="hidden" name="id" value={draft.id}/><textarea name="body" defaultValue={draft.body} rows={5}/><label>Facebook post URL after posting<input name="facebookPostUrl" type="url" placeholder="Optional until posted"/></label><select name="status" defaultValue={draft.status}><option>DRAFT</option><option>APPROVED</option><option>POSTED</option><option>SKIPPED</option></select><button>Save status</button> <a href={draft.group.groupUrl} target="_blank" rel="noreferrer">Open group ↗</a></form></article>)}</div>}
    </section>

    <section className="panel"><h2>Create a group-specific post</h2><form action={generateFacebookGroupContentDraft} className="formGrid"><label>Group<select name="groupId" required>{active.filter(group=>group.outreachPolicy!=="MONITOR_ONLY").map(group=><option value={group.id} key={group.id}>{group.name} — {group.outreachPolicy.replaceAll("_"," ")}</option>)}</select></label><label>Angle<select name="angle"><option value="moving_tip">Useful moving tip</option><option value="delivery_tip">Marketplace delivery tip</option><option value="availability">Local availability</option><option value="community_question">Community question</option></select></label><label>Schedule<input name="scheduledFor" type="datetime-local"/></label><button>Create draft</button></form></section>

    <section className="panel"><h2>Opportunity radar</h2><p>Open a group you already belong to, paste a relevant post, and let the engine classify, score, and deduplicate it.</p>{active.length?<form action={captureFacebookGroupPost} className="formGrid"><label>Group<select name="groupId" required>{active.map(group=><option value={group.id} key={group.id}>{group.name} — {group.region.name}</option>)}</select></label><label>Post URL<input name="postUrl" type="url" required placeholder="https://www.facebook.com/groups/.../posts/..."/></label><label>Author name<input name="authorDisplayName" placeholder="Optional or Anonymous participant"/></label><label>Location<input name="locationText" placeholder="Windsor, ON"/></label><label className="wide">Post text<textarea name="originalText" required rows={5}/></label><label className="wide">Image URLs, one per line<textarea name="imageUrls" rows={2}/></label><label>Posted at<input name="postedAt" type="datetime-local"/></label><button>Classify and add</button></form>:<p>Add a group below first.</p>}</section>

    <section className="panel"><h2>Captured-post review</h2>{posts.length===0?<p>No group posts captured yet.</p>:<div className="cards">{posts.map(post=><article className="card" key={post.id}><div className="cardTop"><div><small>{post.group.name} · {post.group.region.name}</small><h3>{signalLabel[post.opportunityType]??post.opportunityType}</h3></div><strong className="score">{post.opportunityScore}</strong></div><p>{post.originalText}</p><p><b>Why:</b> {post.reasoningSummary}</p>{post.suggestedComment&&<><small>Suggested public response</small><textarea readOnly defaultValue={post.suggestedComment}/></>}{post.suggestedDirectMessage&&<><small>Suggested direct message</small><textarea readOnly defaultValue={post.suggestedDirectMessage}/></>}<p><a href={post.postUrl} target="_blank" rel="noreferrer">Open original post ↗</a> · <b>{post.reviewStatus}</b></p><form action={reviewFacebookGroupPost} className="inlineForm"><input type="hidden" name="id" value={post.id}/><select name="status" defaultValue={post.reviewStatus==="UNREVIEWED"?"APPROVED":post.reviewStatus}><option value="APPROVED">Approved for outreach</option><option value="CONTACTED">Contacted manually</option><option value="MONITORING">Monitor</option><option value="SKIPPED">Skip</option><option value="EXPIRED">Expired</option></select><input name="notes" placeholder="Review note"/><button>Save review</button></form></article>)}</div>}</section>

    <section className="panel"><h2>Group registry and admin playbooks</h2><form action={createFacebookGroup} className="formGrid"><label>Region<select name="regionId" required>{regions.map(region=><option value={region.id} key={region.id}>{region.name}</option>)}</select></label><label>Group name<input name="name" required/></label><label className="wide">Group URL<input name="groupUrl" type="url" required placeholder="https://www.facebook.com/groups/..."/></label><label>Access<select name="accessType"><option>UNKNOWN</option><option>PUBLIC</option><option>PRIVATE</option></select></label><label>Initial rule<select name="outreachPolicy"><option value="REVIEW_RULES">Review group rules</option><option value="COMMENTS_ALLOWED">Business comments allowed</option><option value="DIRECT_MESSAGE_ONLY">Direct message only</option><option value="MONITOR_ONLY">Monitor only</option></select></label><label>Priority<input name="searchPriority" type="number" min="0" max="100" defaultValue="50"/></label><label className="wide">Initial rules summary<textarea name="rulesSummary" rows={2}/></label><button>Add group</button></form>
      <div className="cards">{groups.map(group=><article className="card" key={group.id}><div className="cardTop"><div><h3><a href={group.groupUrl} target="_blank" rel="noreferrer">{group.name}</a></h3><small>{group.region.name} · {group.accessType} · {group.outreachPolicy.replaceAll("_"," ")} · rules: {assessmentStatus(group.rulesAssessment)}</small></div><form action={toggleFacebookGroup}><input type="hidden" name="id" value={group.id}/><input type="hidden" name="enabled" value={String(!group.enabled)}/><button>{group.enabled?"Pause":"Enable"}</button></form></div>
        <p>{group._count.posts} captured posts · {group._count.contentDrafts} content drafts</p>
        <details><summary>Rules and administrator playbook</summary><form action={updateFacebookGroupPlaybook} className="formGrid"><input type="hidden" name="groupId" value={group.id}/><label className="wide">Paste the complete group rules<textarea name="rulesText" rows={6} defaultValue={group.rulesText??""}/></label><label>Admin/moderator name<input name="adminDisplayName" placeholder="Name shown in Members → Admins"/></label><label>Admin profile URL<input name="adminProfileUrl" type="url" placeholder="https://www.facebook.com/..."/></label><label>Role<select name="adminRole"><option>ADMIN</option><option>MODERATOR</option></select></label><button>Assess rules and build playbook</button></form>
          {group.rulesSummary&&<p><b>Assessment:</b> {group.rulesSummary}</p>}
          {group.admins.map(admin=><p key={admin.id}><b>{admin.displayName}</b> · {admin.role} · {admin.contactStatus} {admin.profileUrl&&<>· <a href={admin.profileUrl} target="_blank" rel="noreferrer">Open profile ↗</a></>}</p>)}
          {group.suggestedAdminMessage&&<><small>Suggested administrator message</small><textarea readOnly rows={5} defaultValue={group.suggestedAdminMessage}/><form action={updateFacebookGroupAdminOutreach} className="inlineForm"><input type="hidden" name="groupId" value={group.id}/><input type="hidden" name="adminId" value={group.admins[0]?.id??""}/><select name="status" defaultValue={group.adminOutreachStatus}><option>NOT_CONTACTED</option><option>READY</option><option>CONTACTED</option><option>APPROVED</option><option>DECLINED</option></select><input name="responseNotes" placeholder="Admin response or conditions"/><button>Update admin outreach</button></form></>}
        </details>
      </article>)}</div>
    </section></>
}
