import {prisma} from "@marketplace-engine/database";
import {captureFacebookGroupPost,createFacebookGroup,reviewFacebookGroupPost,toggleFacebookGroup} from "./actions";
export const dynamic="force-dynamic";

const signalLabel:Record<string,string>={direct_request:"Direct request",moving_signal:"Moving signal",property_referral:"Property referral",heavy_item:"Heavy item",competitor:"Competitor",irrelevant:"Irrelevant"};

export default async function FacebookGroups(){
  const [regions,groups,posts]=await Promise.all([
    prisma.region.findMany({where:{enabled:true},orderBy:{name:"asc"}}),
    prisma.facebookGroup.findMany({include:{region:true,_count:{select:{posts:true}}},orderBy:[{enabled:"desc"},{searchPriority:"desc"},{name:"asc"}]}),
    prisma.facebookGroupPost.findMany({include:{group:{include:{region:true}}},orderBy:[{reviewStatus:"asc"},{opportunityScore:"desc"},{firstCapturedAt:"desc"}],take:100})
  ]);
  const unreviewed=posts.filter(post=>post.reviewStatus==="UNREVIEWED"),direct=posts.filter(post=>post.opportunityType==="direct_request"&&post.reviewStatus==="UNREVIEWED");
  return <><header><div><p className="eyebrow">HUMAN-ASSISTED DISCOVERY</p><h1>Facebook Groups</h1><p>Approved groups, captured posts, and contextual response drafts. No groups are joined and no messages are sent automatically.</p></div></header>
    <section className="metrics"><article><small>Approved groups</small><strong>{groups.filter(group=>group.enabled).length}</strong></article><article><small>Unreviewed posts</small><strong>{unreviewed.length}</strong></article><article><small>Direct requests</small><strong>{direct.length}</strong></article><article><small>Qualified 70+</small><strong>{posts.filter(post=>post.opportunityScore>=70&&post.reviewStatus==="UNREVIEWED").length}</strong></article></section>
    <section className="panel"><h2>Capture a post</h2><p>Open a group you already belong to, copy the post URL and text, then let the engine classify and deduplicate it.</p>{groups.filter(group=>group.enabled).length?<form action={captureFacebookGroupPost} className="formGrid"><label>Group<select name="groupId" required>{groups.filter(group=>group.enabled).map(group=><option value={group.id} key={group.id}>{group.name} — {group.region.name}</option>)}</select></label><label>Post URL<input name="postUrl" type="url" required placeholder="https://www.facebook.com/groups/.../posts/..."/></label><label>Author name<input name="authorDisplayName" placeholder="Optional"/></label><label>Location<input name="locationText" placeholder="Windsor, ON"/></label><label className="wide">Post text<textarea name="originalText" required rows={5} placeholder="Paste the complete post text and important caption details"/></label><label className="wide">Image URLs, one per line<textarea name="imageUrls" rows={2} placeholder="Optional"/></label><label>Posted at<input name="postedAt" type="datetime-local"/></label><button>Classify and add to review</button></form>:<p>Add an approved group below before capturing posts.</p>}</section>
    <section className="panel"><h2>Review queue</h2>{posts.length===0?<p>No group posts captured yet.</p>:<div className="cards">{posts.map(post=><article className="card" key={post.id}><div className="cardTop"><div><small>{post.group.name} · {post.group.region.name}</small><h3>{signalLabel[post.opportunityType]??post.opportunityType}</h3></div><strong className="score">{post.opportunityScore}</strong></div><p>{post.originalText}</p><p><b>Why:</b> {post.reasoningSummary}</p>{post.suggestedComment&&<><small>Suggested public response</small><textarea readOnly defaultValue={post.suggestedComment}/></>}{post.suggestedDirectMessage&&<><small>Suggested direct message</small><textarea readOnly defaultValue={post.suggestedDirectMessage}/></>}<p><a href={post.postUrl} target="_blank" rel="noreferrer">Open original Facebook post ↗</a> · <b>{post.reviewStatus}</b></p><form action={reviewFacebookGroupPost} className="inlineForm"><input type="hidden" name="id" value={post.id}/><select name="status" defaultValue={post.reviewStatus==="UNREVIEWED"?"APPROVED":post.reviewStatus}><option value="APPROVED">Approved for outreach</option><option value="CONTACTED">Contacted manually</option><option value="MONITORING">Monitor</option><option value="SKIPPED">Skip</option><option value="EXPIRED">Expired</option></select><input name="notes" placeholder="Review note"/><button>Save review</button></form></article>)}</div>}</section>
    <section className="panel"><h2>Approved group registry</h2><form action={createFacebookGroup} className="formGrid"><label>Region<select name="regionId" required>{regions.map(region=><option value={region.id} key={region.id}>{region.name}</option>)}</select></label><label>Group name<input name="name" required/></label><label className="wide">Group URL<input name="groupUrl" type="url" required placeholder="https://www.facebook.com/groups/..."/></label><label>Access<select name="accessType"><option>UNKNOWN</option><option>PUBLIC</option><option>PRIVATE</option></select></label><label>Outreach rule<select name="outreachPolicy"><option value="REVIEW_RULES">Review group rules</option><option value="COMMENTS_ALLOWED">Business comments allowed</option><option value="DIRECT_MESSAGE_ONLY">Direct message only</option><option value="MONITOR_ONLY">Monitor only</option></select></label><label>Priority<input name="searchPriority" type="number" min="0" max="100" defaultValue="50"/></label><label className="wide">Rules summary<textarea name="rulesSummary" rows={2}/></label><button>Add approved group</button></form><table><thead><tr><th>Group</th><th>Region</th><th>Access</th><th>Outreach policy</th><th>Posts</th><th>Status</th></tr></thead><tbody>{groups.map(group=><tr key={group.id}><td><a href={group.groupUrl} target="_blank" rel="noreferrer">{group.name}</a></td><td>{group.region.name}</td><td>{group.accessType}</td><td>{group.outreachPolicy.replaceAll("_"," ")}</td><td>{group._count.posts}</td><td><form action={toggleFacebookGroup} className="inlineForm"><input type="hidden" name="id" value={group.id}/><input type="hidden" name="enabled" value={String(!group.enabled)}/><button>{group.enabled?"Pause":"Enable"}</button></form></td></tr>)}</tbody></table></section></>
}
